name: build
on: [push]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: src/build.sh x64 release
    - uses: actions/upload-artifact@v2
      with:
        name: libInstrumentationEngine.dylib
        path: out/OSX/bin/x64.Release/ClrInstrumentationEngine/libInstrumentationEngine.dylib
