name: build
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: src/build.sh x64 release
    - uses: actions/upload-artifact@v2
      with:
        name: libInstrumentationEngine.so
        path: out/Linux/bin/x64.Release/ClrInstrumentationEngine/libInstrumentationEngine.so
